# Generated by Django 4.1.7 on 2023-04-06 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMCS', '0003_remove_doctor_certificate_remove_doctor_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pincode',
            field=models.CharField(default=123456, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian pincode.', regex='^[0-9]{6}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian pincode.', regex='^[0-9]{6}$')]),
        ),
    ]
