# Generated by Django 4.1.7 on 2023-04-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMCS', '0004_doctor_pincode_alter_hospital_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='afternoontoken',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='eveninggtoken',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='morningtoken',
        ),
        migrations.AddField(
            model_name='bookedappointments',
            name='appointment_preference',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
