# Generated by Django 4.1.7 on 2023-04-07 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMCS', '0006_doctor_password_patient_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='pending_doctors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=100000)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('phone_number', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100)),
                ('specialization', models.IntegerField(default=0)),
                ('pincode', models.CharField(default=111111, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian pincode.', regex='^[0-9]{6}$')])),
                ('age', models.PositiveIntegerField(default=0)),
                ('experience', models.CharField(default='', max_length=100)),
                ('isdelete', models.BooleanField(default=False)),
                ('hospitalid', models.IntegerField(default=0)),
            ],
        ),
    ]
