# Generated by Django 4.1.7 on 2023-07-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OMCS", "0007_admin_pending_doctors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="isdelete",
        ),
    ]
