# Generated by Django 4.1.7 on 2023-07-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OMCS", "0008_remove_hospital_isdelete"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedappointments",
            name="time",
            field=models.TimeField(default="00:00"),
        ),
    ]
